### ISSUE TITLE
Drop remaining items from 2x2 crafting grid

### ISSUE THREAD

**Issue by tacotexmex** [danielmeek32/craftingtable#1]
Just like items drop from the crafting table when exiting the formspec, the sfinv crafting grid should exhibit the same behavior. The items could be added back to the player inventory if there's room still and drop the rest.

**Comment by danielmeek32** [comment]
Interesting idea, I'll think about it.

My approach to modding is usually to implement the idea of the mod while changing as little of the surrounding gameplay mechanics or behaviors as possible, and the reason why the items drop from the crafting table was simply to find an easy way around the issue of resizing the crafting inventory/grid while there were items in it. It has also occurred to me that, if the player opens the crafting table grid while they have items in their 2x2 crafting grid, those items will actually appear in the crafting table grid, which may be confusing or look unpolished to some players.

There are a number of ways that these situations could be handled. The ones that immediately come to mind are:

1. Keep as many items as possible in the grid while returning the rest to the player's inventory (if possible, dropping those that won't fit).
2. Return all the items to the player's inventory (if possible, dropping those that won't fit).
3. Always drop the items even if there is room in the player's inventory.

It might be desirable to have one behavior for the crafting grid in the player's inventory and another behavior for the crafting table (e.g. return items to the player's inventory from the internal crafting grid, but drop items on the ground from the crafting table). I think the most flexible approach would be to implement all three of the above behaviors and provide one configuration option to choose a behavior for closing the player's inventory and another configuration option to choose a behavior for closing the crafting table. For default configuration choices, I like behavior 2 for closing the player's inventory and behavior 3 for closing the crafting table.

I will look at implementing this when I get the chance.

**Comment by tacotexmex** [comment]
> For default configuration choices, I like behavior 2 for closing the player's inventory and behavior 3 for closing the crafting table.

Excellent, this is what I had in mind. Thank you!
